### ISSUE TITLE
Hakutoiminto

### ISSUE THREAD

**Issue by japsu** [kcsry/infokala#16]

**Comment by shadikka** [comment]
Speksattu: Hakutoiminto ei lähtökohtaisesti palauta jo hoidettuja hommia, mutta on vaihtoehto.

**Comment by shadikka** [comment]
Ennen kuin on teknisesti järkevää etsiä kommenteista yms. pelkän jo sivulla valmiiksi olevan tiedon lisäksi, ei ole minkäänlaista järkeä koodata erillistä hakutoimintoa, kun selaimissa on sellainen jo valmiiksi. Koska kommentit lazy-loadataan, niin ainoastaan edellisen sivun päivityksen jälkeen avattujen tehtävien kommentit (ja muutostapahtumat) ovat käytettävissä, eikä ole missään nimessä tarkoituksenmukaista hakea vain *osasta* kommentteja.
