### ISSUE TITLE
Eri viestityyppien erottelu taustavärillä

### ISSUE THREAD

**Issue by japsu** [kcsry/infokala#17]
Traconin infovastaava esitti seuraavanlaisen toiveen:

> Itse toivoisin että erilaiset lokit olisi erivärisillä taustoilla, näin olisi helpompi etsiä koko lokin seasta et mitkä on esim löytöravaroita. Jotain pehmeitä värejä, ei tartte olla kirkkaan punainen :DD

**Comment by akx** [comment]
Oiskohan joku subtlempi, esim. viestin yhden (vasemman?) borderin värjäys riittävä? Meinaan jos joka viesti on omalla värillään, saattaa lukeminen olla hankalampaa.

**Comment by japsu** [comment]
Joo toi border vois olla hyvä. Täytyy protoilla jossain vaiheessa kun taas
ehtii tätä.

2015-08-04 21:01 GMT+03:00 Aarni Koskela notifications@github.com:

> Oiskohan joku subtlempi, esim. viestin yhden (vasemman?) borderin värjäys
> riittävä? Meinaan jos joka viesti on omalla värillään, saattaa lukeminen
> olla hankalampaa.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kcsry/infokala/issues/17#issuecomment-127693628.

## 

Santtu Pajukanta

**Comment by shadikka** [comment]
Info kaipaa tätä Frostbiteen.

**Comment by shadikka** [comment]
(Info ei saanut tätä Frostbiteen. :stuck_out_tongue_winking_eye:)
