### ISSUE TITLE
Kun edellisen vuorokauden puolella lähetettyä viestiä muokkaa tai kommentoi vuorokauden vaihduttua, Kaaos voittaa conipelin

### ISSUE THREAD

**Issue by japsu** [kcsry/infokala#28]

**Comment by akx** [comment]
Avannet tätä jossain vaiheessa? :D

**Comment by japsu** [comment]
No siis. Otsikko on päätelty voimakkaan korrelaation (N=1, p=1.0) perusteella, joskaan kausaliteettia ei oo ihan vielä voitu osoittaa.

Kun edellisen vuorokauden puolella lähetettyä viestiä muokkaa tai kommentoi, lokiin tulee useita "Vuorokausi: xx/xx/xxxx"-viestejä. Tästä seurannut, no, kaaos, sataa suoraan Kaaoksen laariin.

Odotetut tulokset: Järjestys voittaa conipelin

Todelliset tulokset: Kaaos voittaa conipelin

**Comment by japsu** [comment]
```
aketzu [09:45]  
japsu: hassu infokala... tuolla on päivämäärä 7/30/2016 ja 7/31/2016 rivejä monta... 9 kertaa vaihtunu päivä viime yönä :)

japsu [09:53]  
Jahas, kirjataam bugi

[09:53]  
Minen tuosta featuresta tiedä mi-tään ko sen on toteuttan @shadikka

aketzu [10:35]  
haa... päivämäärä-triggeri katsoo varmaankin updated-at leimaa ja jos tossa ennen puoltayötä tehdään taskeja/löytötavaroita jotka merkataan valmiiksi vasta seuraavan vuorokauden puolella.

[10:37]  
japsu: ^ lisääks tikettiin ton arvauksen

japsu [10:37]  
Lisään, kiitos.
```

**Comment by shadikka** [comment]
Fiksattu ES2015-päivityksen yhteydessä. Hypoteesi oli oikein, ks. https://github.com/kcsry/infokala/blob/6dc3f8bd394561b62af5ba9602f985edcca681bc/infokala/static_src/infokala/main_view_model.js#L141
