### ISSUE TITLE
Latausindikaattori

### ISSUE THREAD

**Issue by japsu** [kcsry/infokala#31]
Kun viestejä on paljon (esim. Traconin infolokin lataaminen tapahtuman jälkeen), initial load voi kestää kymmenisen sekuntia. Tästä ois kiva näyttää käyttäjälle joku pendeli.

**Comment by akx** [comment]
10 sekuntia kuulostaa pitkältä ajalta joka tapauksessa.

Low hanging fruit lienee lisätä `.select_related()` [tänne](https://github.com/kcsry/infokala/blob/fb5911c29831b8ef24524fc1fc687a1adf9498fd/infokala/views.py#L192) (ja vastaaviin paikkoihin; harkitsisin `Message`n Manageriin `common_select_related()` tms lisäämistä), ja [valita sinne ainakin `message_type`, `created_by`, `updated_by`, `deleted_by`, `state` sekä annotoida queryset kommenttien lukumääräaggregaatilla](https://github.com/kcsry/infokala/blob/fb5911c29831b8ef24524fc1fc687a1adf9498fd/infokala/models.py#L180-L199) .

**Comment by akx** [comment]
Montako viestiä Traconilla btw on, @japsu? Summanmutikka-arvo käy myös.

**Comment by japsu** [comment]
Eipä siinä näköjään nopeella netillä ja cachet lämmitettyinä kestäkään näköjään kuin sekunti API-hakuun. 286 viestiä. Jonkin verran aikaa menee Javascript-pyörittelyyn kun Knockout ei ole suorituskyvyltään ihan paras.

Kuitenkin hetken aikaa käyttöliittymä hengaa tyhjänä ilman mitään selitystä, se on tässä se jota haluaisin parantaa.

**Comment by japsu** [comment]
Ja joo, kannattaa ilman muuta tuupata sinne tuo `.select_related`
