### ISSUE TITLE
Use multi-stage build

### ISSUE THREAD

**Issue by japsu** [kcsry/infokala#37]
Using a new Docker feature called multi-stage build we can build the Javascript deps using one base image and then copy them into an image that only has the runtime Python dependencies.

https://docs.docker.com/engine/userguide/eng-image/multistage-build/

Pseudo-`Dockerfile`:

```
FROM node
RUN install javascript deps
RUN build bundle.js
EXPORT bundle.js

FROM python
IMPORT bundle.js
RUN install python deps
CMD python manage.py runserver
```

**Comment by akx** [comment]
Oh, that's a nice feature!

**Comment by akx** [comment]
I think this is obsolete now that the CI process builds wheels (that contain precompiled JavaScript) and the GH releases have wheels attached: https://github.com/kcsry/infokala/releases/tag/v0.5.1
